// Generated by CoffeeScript 1.6.2
(function() {
  test("to_d3", function() {
    var expected_d3, node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Earth Programmer": 0.5,
      "Earth Engineer": 0.6
    });
    expected_d3 = {
      "name": "Joan of Arc",
      "children": [
        {
          "name": "Earth Programmer",
          "size": 0.5
        }, {
          "name": "Earth Engineer",
          "size": 0.6
        }
      ]
    };
    return deepEqual(node_tree.to_d3(), expected_d3);
  });

  test("color it red", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 1
    });
    return equal(node_tree.color(), '#ff0000');
  });

  test("color it blue", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Blue": 1
    });
    return equal(node_tree.color(), '#0000ff');
  });

  test("color it purple (mixing red and blue)", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Blue": 1,
      "Red": 1
    });
    return equal(node_tree.color(), '#ff00ff');
  });

}).call(this);
