// Generated by CoffeeScript 1.6.2
(function() {
  test("to_d3", function() {
    var expected_d3, node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Earth Programmer": 0.5,
      "Earth Engineer": 0.6
    });
    expected_d3 = {
      "name": "Joan of Arc",
      "children": [
        {
          "name": "Earth Programmer",
          "size": 0.5
        }, {
          "name": "Earth Engineer",
          "size": 0.6
        }
      ]
    };
    return deepEqual(node_tree.to_d3(), expected_d3);
  });

  test("hex_color when no color information is present", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Earth Programmer": 1
    });
    return equal(node_tree.hex_color(), '#000000');
  });

  test("hex_color it black", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Black": 1
    });
    return equal(node_tree.hex_color(), '#000000');
  });

  test("hex_color it red", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 1
    });
    return equal(node_tree.hex_color(), '#ff0000');
  });

  test("hex_color it blue", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Blue": 1
    });
    return equal(node_tree.hex_color(), '#0000ff');
  });

  test("hex_color it purple (mixing red and blue)", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Blue": 1,
      "Red": 1
    });
    return equal(node_tree.hex_color(), '#ff00ff');
  });

  test("hex_color mixing and normalization", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 1,
      "Purple": 1
    });
    return equal(node_tree.hex_color(), '#ff0055');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 0.5,
      "green": 0
    });
    return equal(node_tree.hex_color(), '#800000');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 1,
      "green": 0
    });
    return equal(node_tree.hex_color(), '#ff0000');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 2,
      "green": 0
    });
    return equal(node_tree.hex_color(), '#ff0000');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "red": 1,
      "blue": 1
    });
    return equal(node_tree.hex_color(), '#ff00ff');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "Red": 2,
      "Blue": 1
    });
    return equal(node_tree.hex_color(), '#ff0080');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "red": 4,
      "blue": 1
    });
    return equal(node_tree.hex_color(), '#ff0040');
  });

  test("hex_color weights", function() {
    var node_tree;

    node_tree = new NodeTree("Joan of Arc", {
      "red": 0.5,
      "blue": 1 / 3
    });
    return equal(node_tree.hex_color(), '#800055');
  });

}).call(this);
