// Generated by CoffeeScript 1.6.2
(function() {
  test("node_trees_to_d3", function() {
    return deepEqual(node_trees_to_d3({
      "": {
        "is": ["Joan of Arc"],
        "Tag": ["Earth Programmer"]
      },
      "De-coder and Coder": {
        "Tag": ["Earth Programmer"]
      }
    }), {
      "name": "Joan of Arc",
      "children": [
        {
          "name": "Tag",
          "children": [
            {
              "name": "Earth Programmer",
              "size": 3
            }
          ]
        }
      ]
    });
  });

}).call(this);
