// Generated by CoffeeScript 1.6.2
(function() {
  var root,
    __hasProp = {}.hasOwnProperty;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.NodeTree = (function() {
    function NodeTree(name, properties) {
      this.name = name;
      this.properties = properties;
      if (typeof this.name !== "string") {
        throw "ArgumentException";
      }
      if (!(this.properties instanceof Object)) {
        throw "ArgumentException";
      }
    }

    NodeTree.prototype.to_d3 = function() {
      var property_name, weight;

      return {
        "name": this.name,
        "children": (function() {
          var _ref, _results;

          _ref = this.properties;
          _results = [];
          for (property_name in _ref) {
            if (!__hasProp.call(_ref, property_name)) continue;
            weight = _ref[property_name];
            if (property_name) {
              _results.push({
                "name": property_name,
                "size": weight
              });
            }
          }
          return _results;
        }).call(this)
      };
    };

    return NodeTree;

  })();

}).call(this);
